export default [
  {
    label: "Button",
    properties: {
      tag: "button",
      content: "Button",
      sectionName: "Button",
      styles: {
        marginLeft: 5,
        marginRight: 5,
        marginTop: 1,
        marginBottom: 1,
        background: "#5599ff",
        border: "none",
        outline: "none",
        borderRadius: 10,
        paddingTop: 5,
        paddingLeft: 15,
        paddingBottom: 5,
        paddingRight: 15,
        fontWeight: 700,
        letterSpacing: 1.5,
        textTransform: "uppercase",
        color: "#ffffff",
        fontSize: 14,
      },
    },
  },
  {
    label: "Heading 1",
    properties: {
      tag: "h1",
      content: "Heading 1",
      sectionName: "Heading 1",
      styles: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 5,
        marginBottom: 5,
        background: "inherit",
        paddingTop: 0,
        paddingLeft: 0,
        paddingBottom: 0,
        paddingRight: 0,
        fontWeight: 700,
        letterSpacing: 1.5,
        color: "inherit",
        fontSize: 32,
      },
    },
  },
  {
    label: "Pragraph",
    properties: {
      tag: "p",
      content: "Pragraph",
      sectionName: "Pragraph",
      styles: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 5,
        marginBottom: 5,
        background: "inherit",
        paddingTop: 0,
        paddingLeft: 0,
        paddingBottom: 0,
        paddingRight: 0,
        fontWeight: 500,
        letterSpacing: 0.7,
        color: "inherit",
        fontSize: 14,
      },
    },
  },
  {
    label: "List",
    properties: {
      tag: "ul",
      content: "List",
      sectionName: "Heading 1",
      styles: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
        background: "inherit",
        paddingTop: 0,
        paddingLeft: 0,
        paddingBottom: 0,
        paddingRight: 0,
        color: "inherit",
      },
    },
  },
  {
    label: "List Items",
    properties: {
      tag: "li",
      content: "Item",
      sectionName: "List Item",
      styles: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
        background: "inherit",
        paddingTop: 0,
        paddingLeft: 10,
        paddingBottom: 0,
        paddingRight: 10,
        color: "inherit",
      },
    },
  },
  {
    label: "Image",
    properties: {
      tag: "img",
      content: "",
      attributes: {
        src: "https://images2.imgbox.com/3e/9e/RdL8UabE_o.png",
      },
      sectionName: "Image",
      styles: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
        paddingTop: 0,
        paddingLeft: 0,
        paddingBottom: 0,
        overflow: "hidden",
        paddingRight: 0,
      },
    },
  },
];
